name = "qwen-code-cli-wrapper"
main = "src/index.ts"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

# --- KV Namespaces ---
kv_namespaces = [
  { binding = "QWEN_KV", id = "f3eb5ce9c83143d69ddff79f458b0de1" }
]


# --- Local Development Configuration ---
# This section configures local development with Docker and miniflare
[dev]
ip = "0.0.0.0"          # Bind to all interfaces for Docker access
port = 8787             # Port for local development server
# Note: --persist-to flag in Docker handles storage location

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true